permalink: /:categories/:year/:month/:day/:title.html

auto: false
pygments: false
markdown: redcarpet

#markdown: rdiscount
#markdown: redcarpet
#markdown: kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
